{% set name = "lavavu" %}
{% set version = "1.6.1" %}

package:                                                  
  name: "{{ name|lower }}"
  version: "{{ version }}"                                     

source:                                                     
    git_url: https://github.com/lavavu/LavaVu.git

build:
  number: 0
  entry_points:
    - LV = lavavu.__main__:main
    - LavaVu = lavavu.__main__:main
  script: "{{ PYTHON }} -m pip install . -vv"     

requirements:
  host:
    - aiohttp
    - jupyter-server-proxy
    - numpy >=1.11
    - pip
    - python
  run:
    - aiohttp
    - jupyter-server-proxy
    - numpy >=1.11
    - python

test:
  imports:
    - lavavu
  commands:
    - LV --help
    - LavaVu --help

about:
  home: "https://github.com/lavavu/LavaVu"
  license: "GNU Lesser General Public v3 (LGPLv3)"
  license_family: LGPL
  license_file:
  summary: "Python interface to LavaVu OpenGL 3D scientific visualisation utilities"
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - yohanderose