{% set name = "lavavu" %}
{% set version = "1.6.2" %}

package:                                                  
  name: "{{ name|lower }}"
  version: "{{ version }}"                                     

source:                                                     
    git_url: https://github.com/lavavu/LavaVu.git

build:
  number: 0
  script: "{{ PYTHON }} -m pip install ."     

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
  run:
    - aiohttp
    - jupyter-server-proxy
    - numpy
    - python

test:
  imports:
    - lavavu

about:
  home: "https://github.com/lavavu/LavaVu"
  license: "GNU Lesser General Public v3 (LGPLv3)"
  license_family: LGPL
  license_file:
  summary: "Python interface to LavaVu OpenGL 3D scientific visualisation utilities"
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - yohanderose